export var __esModule: boolean;
export function getControllers(options: any): {
    loggerController: _LoggerController.LoggerController;
    filesController: _FilesController.FilesController;
    userController: _UserController.UserController;
    pushController: _PushController.PushController;
    hasPushScheduledSupport: boolean;
    hasPushSupport: boolean;
    pushWorker: _PushWorker.PushWorker;
    pushControllerQueue: _PushQueue.PushQueue;
    analyticsController: _AnalyticsController.AnalyticsController;
    cacheController: _CacheController.CacheController;
    parseGraphQLController: any;
    liveQueryController: _LiveQueryController.LiveQueryController;
    databaseController: any;
    hooksController: _HooksController.HooksController;
    authDataManager: any;
    schemaCache: any;
};
export function getLoggerController(options: any): _LoggerController.LoggerController;
export function getFilesController(options: any): _FilesController.FilesController;
export function getUserController(options: any): _UserController.UserController;
export function getCacheController(options: any): _CacheController.CacheController;
export function getParseGraphQLController(options: any, controllerDeps: any): any;
export function getAnalyticsController(options: any): _AnalyticsController.AnalyticsController;
export function getLiveQueryController(options: any): _LiveQueryController.LiveQueryController;
export function getDatabaseController(options: any): any;
export function getHooksController(options: any, databaseController: any): _HooksController.HooksController;
export function getPushController(options: any): {
    pushController: _PushController.PushController;
    hasPushSupport: boolean;
    hasPushScheduledSupport: boolean;
    pushControllerQueue: _PushQueue.PushQueue;
    pushWorker: _PushWorker.PushWorker;
};
export function getAuthDataManager(options: any): any;
export function getDatabaseAdapter(databaseURI: any, collectionPrefix: any, databaseOptions: any): any;
import _LoggerController = require("./LoggerController");
import _FilesController = require("./FilesController");
import _UserController = require("./UserController");
import _PushController = require("./PushController");
import _PushWorker = require("../Push/PushWorker");
import _PushQueue = require("../Push/PushQueue");
import _AnalyticsController = require("./AnalyticsController");
import _CacheController = require("./CacheController");
import _LiveQueryController = require("./LiveQueryController");
import _HooksController = require("./HooksController");
