# Trigger this workflow only to manually create a docs release; this should only be used
# in extraordinary circumstances, as docs releases are normally created automatically as
# part of the automated release workflow.

name: release-manual-docs
on:
  workflow_dispatch:
    inputs:
      ref:
        default: ''
        description: 'Reference (tag / SHA):'
        required: true
jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.4
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-node-
      - name: Generate Docs
        run: |
          echo $SOURCE_TAG
          npm ci
          ./release_docs.sh
        env:
          SOURCE_TAG: ${{ github.event.inputs.ref }}
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
